name: ecowatt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  sticky_headers: ^0.3.0+2
  aes_crypt_null_safe: ^3.0.0
  encrypt: ^5.0.3
  shared_preferences: ^2.3.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_core: ^2.31.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/ecowatt.jpeg
    - assets/image/img.png
    - assets/image/robot.png
