// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0VSL1_jyJxs-LUB3BwVXJc-Eo5wnW3YE',
    appId: '1:398430500707:web:03d693a727945fb0ed0556',
    messagingSenderId: '398430500707',
    projectId: 'ecowatt-85d34',
    authDomain: 'ecowatt-85d34.firebaseapp.com',
    databaseURL: 'https://ecowatt-85d34-default-rtdb.firebaseio.com',
    storageBucket: 'ecowatt-85d34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzM5zPwFO1q2kMjIZ6n9BcLm2UTWaKj2E',
    appId: '1:398430500707:android:d4122f76660fca2bed0556',
    messagingSenderId: '398430500707',
    projectId: 'ecowatt-85d34',
    databaseURL: 'https://ecowatt-85d34-default-rtdb.firebaseio.com',
    storageBucket: 'ecowatt-85d34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeXFFr74qnh9M8ZpEbmlvrdnRYfpEHmZY',
    appId: '1:398430500707:ios:312bba4708117341ed0556',
    messagingSenderId: '398430500707',
    projectId: 'ecowatt-85d34',
    databaseURL: 'https://ecowatt-85d34-default-rtdb.firebaseio.com',
    storageBucket: 'ecowatt-85d34.appspot.com',
    iosClientId: '398430500707-839lrpbgg6m9c2a8etsts4poh529dsns.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecowatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeXFFr74qnh9M8ZpEbmlvrdnRYfpEHmZY',
    appId: '1:398430500707:ios:312bba4708117341ed0556',
    messagingSenderId: '398430500707',
    projectId: 'ecowatt-85d34',
    databaseURL: 'https://ecowatt-85d34-default-rtdb.firebaseio.com',
    storageBucket: 'ecowatt-85d34.appspot.com',
    iosClientId: '398430500707-839lrpbgg6m9c2a8etsts4poh529dsns.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecowatt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0VSL1_jyJxs-LUB3BwVXJc-Eo5wnW3YE',
    appId: '1:398430500707:web:d57349705dbdb7e3ed0556',
    messagingSenderId: '398430500707',
    projectId: 'ecowatt-85d34',
    authDomain: 'ecowatt-85d34.firebaseapp.com',
    databaseURL: 'https://ecowatt-85d34-default-rtdb.firebaseio.com',
    storageBucket: 'ecowatt-85d34.appspot.com',
  );
}
